name: Code Quality

on: [push, pull_request]

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.1
        with:
          node-version: '14.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run post Install
        run: npm run postinstall

      - name: Run Prettier
        run: npm run prettier

  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1.4.1
        with:
          node-version: '14.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run post Install
        run: npm run postinstall

      - name: Run ESLint
        run: npm run lint
