name: Code Quality

on: [push, pull_request]

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.0
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: '14.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run post Install
        run: npm run postinstall

      - name: Run Prettier
        run: npm run prettier

  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.0

      - uses: actions/setup-node@v2.1.0
        with:
          node-version: '14.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run post Install
        run: npm run postinstall

      - name: Run ESLint
        run: npm run lint

  Test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        node: ['14.x']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.0

      - uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run post Install
        run: npm run postinstall

      - name: Run Tests
        run: npm run test
